### ISSUE TITLE
Docs refer to non-existing config option 'table_mode'

### ISSUE THREAD

**Issue by emil-e** [nushell/nushell.github.io#1007]
### Describe the bug

These docs:
https://www.nushell.sh/book/coloring_and_theming.html#table-borders

Refer to `table_mode` but these days it seems to be `table.mode`.

### How to reproduce

Read the docs, try doing what it says.

### Expected behavior

Docs to match released code.

### Configuration

Not relevant

**Comment by hustcer** [comment]
@emil-e Thanks, the issue has been transferred to Nushell docs repo, and PRs are welcomed

**Comment by fdncred** [comment]
You're right, it's now `$env.config.table.mode`. We rearranged some things since I wrote that page. It probably deserves a good cleanup.
