### ISSUE TITLE
When the environment variable Path is modified

### ISSUE THREAD

**Issue by sucls** [nushell/nushell.github.io#1027]
The system environment variable was modified, but it did not take effect!!

**Comment by fdncred** [comment]
1. Did you mean to put this in the docs repository?
2. We need an example of what you're talking about.

**Comment by sholderbach** [comment]
Closing this issue as it is too vague for others to follow and in the wrong place.

If you have a bug or specific question about nushell's behavior please check the  [main nushell](https://github.com/nushell/nushell) repo and file an issue there with the appropriate information to reproduce.
