### ISSUE TITLE
Documentation for 'def' keyword signature should include optional syntax for the return type of the custom command

### ISSUE THREAD

**Issue by edhowland** [nushell/nushell.github.io#1035]
### Describe the bug

Custom commands defined using the 'def' keyword allow, in addition to specifying
the  optional parameter types, also allow for specifying an optional return
type. E.g.

```sh
# returns the square of the parameter
def square [x: int] -> int {
  $x * $x
}
```

The '-> <type>'  is not mentioned in any of the documentation for either
the 'def' keyword or the Nushell book chapter on  Custom Commands:

## The def keyword

https://www.nushell.sh/commands/docs/def.html

Note: The same text as in the command reference for the 'def' keyword is output
when you type:

```sh
help def
```

and should also include the optional '-> <type> part of the signature.

## The Custom Command chapter

https://www.nushell.sh/book/custom_commands.html

In the command reference or the help text there should be:

1. Part of the signature between the parameters and the body should be the return type.
2. Examples of using the 'def' keyword should include an example with the '-> <type>
  * Perhaps like the square example above.

In the chapter on "Custom Commands",
there should be a  Heading 2 section called something like

## Specifying the return type of your command

Custom commands can optionally specify their return type which helps the Nushell
compiler to check your usage when calling your custom command especially in an expression.

Eg. Say we just want to format our greeting like this:

```sh
def fmt-greet [name: string] -> string {
  $"Hello ($name)"
}```

Then for another command that takes a greeting as input:

```sh
def print-greeting [greeting: string] {
  echo $"When you greet someone, you should say: '($greet)'"
}

# then to call it
print-greet (fmt-greet "Fred")
```

### How to reproduce

This is just a documentation ommision. There is no steps to reproduce this bug. Just  add the missing documentation.

### Expected behavior

The documentation on the web site for the Nushell book and the command reference should be updated to include the optional return type syntax for defining custom commands. This should also be included in the help text for the 'def' keyword.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          || features           | dataframe, default, sqlite, trash, which, zip                     || installed_plugins  |                                                                   |

**Comment by OrionOth** [comment]
With #1167, this should now be halfway done; while not documented in the `def` command documentation, it is documented in [`command_signatures.md`](https://github.com/nushell/nushell.github.io/blob/main/book/command_signature.md). I think in the future, that documentation page should be integrated with other parts of the documentation; probably as part of a larger documentation restructuring.

**Comment by NotTheDr01ds** [comment]
Added the other half in https://github.com/nushell/nushell/pull/13561 that will hopefully close this out.
