### ISSUE TITLE
Documention example for migrating from xargs

### ISSUE THREAD

**Issue by srgfrog** [nushell/nushell.github.io#1036]
Is it possible to include this example to book/coming_from_bash.html, to demonstrates how to migrate xargs?

```
ls -Q ~/Downloads/*.mp4 |  xargs  mpv --shuffle --vid=no

(ls ~/Downloads/*.mp4).name   | run-external  "mpv" "--shuffle" "--vid=no" $in
```

**Comment by sholderbach** [comment]
Feel free to open a PR along those lines. I would recommend that the example only uses well known programs so you don't need to look for the example or install it to try.
