### ISSUE TITLE
Make generated command pages point to the right place for editing

### ISSUE THREAD

**Issue by alsuren** [nushell/nushell.github.io#1041]
Unfortunately, any change to commands/docs gets rejected because those docs are generated from the commands themselves with each new release. If you want to change the help for a command like this, you'll need to change the rust code and then when we auto-generate, it'll appear in here.

_Originally posted by @fdncred in https://github.com/nushell/nushell.github.io/issues/1040#issuecomment-1703838807_
            

Currently https://www.nushell.sh/commands/docs/keybindings.html has a link to `Edit this page on GitHub` which points at https://github.com/nushell/nushell.github.io/edit/main/commands/docs/keybindings.md . I followed its instructions and opened https://github.com/nushell/nushell.github.io/issues/1040 but then I had to close it and open https://github.com/nushell/nushell/pull/10193 instead.

Options include:
a) make the generated keybindings.md contain a `<!-- comment -->` pointing at the location in the rust code where the source of truth is (even just pointing at the repo would probably be enough).
b) somehow disable the mdbook-generated `Edit this page on GitHub` link to avoid confusion. (not sure if it's possible to do on just hte commands/docs subtree. I've not looked)

**Comment by fdncred** [comment]
I believe the CI failures are intended to tell people about making links in commands/docs
