### ISSUE TITLE
There seems not to be any document about path as a type.

### ISSUE THREAD

**Issue by otakutyrant** [nushell/nushell.github.io#1044]
Altough it is confirmed that [path is a type and a command](https://github.com/nushell/nushell/discussions/10203) simutaneously. [Types of Data](https://www.nushell.sh/book/types_of_data.html) does not include path, and [path](https://www.nushell.sh/commands/categories/path.html) only regards itself as a command.

**Comment by fdncred** [comment]
Technically `path` is not a type. You can see the nushell types here:

https://github.com/fdncred/nushell/blob/main/crates/nu-protocol/src/ty.rs#L9-L37

It is a `SyntaxShape` as you can see here:

https://github.com/fdncred/nushell/blob/main/crates/nu-protocol/src/syntax_shape.rs#L7-L119

and here:

https://github.com/fdncred/nushell/blob/main/crates/nu-parser/src/parser.rs#L2685-L2765

I'm not sure all of these can be used as "types" in custom commands. I thought there was another list for custom commands but I can't seem to find it now. Maybe someone else has an idea.

**Comment by otakutyrant** [comment]
The real X question is that I want to define the shape of an argument of an extern command `stow` as directories only so that I can complete the command with directories names only. So I want to check the document of the "type" `path` to see whether I can find the appropriate type.
