### ISSUE TITLE
Change Python shebang in Contributer's book chapter on plugins to be more portable

### ISSUE THREAD

**Issue by edhowland** [nushell/nushell.github.io#1059]
The Python example on the page:
[https://www.nushell.sh/contributor-book/plugins.html](https://www.nushell.sh/contributor-book/plugins.html)
should have a better shebang line. Currently, the shebang line reads like this 
(first line of the code):

```python
#!/usr/local/bin/python3

```

This shebang line is not portable. It should read like this:

```python
#!/usr/bin/env python3
````

I have tried this out on the following OSes:

1. MacOS:
  *Ventura
2. Debian 
  *Bullseye/v11
3. Ubuntu 
  * 18.04
4. RaspberryOS: 
  * Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/

There will be a matching PR with this. I will add that number as a further
comment below.

AFAIK, this does not effect Windows except in WSL in which the above OSes apply.

The best Python resource on this subject I found is:

[https://realpython.com/python-shebang/](https://realpython.com/python-shebang/)

For more on this:

[https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my)

The upshot of all this discussion is that '#!/usr/bin/env python3' shebang
will use the  python3 on the user's $PATH. If they have multiple Pythons
installed, whichever is first in the $PATH. AFAIK, when Nushell loadds,
the variable '$env.PATH' is inherited from '$PATH' in the system environment.
Thus, when you run 'register <path-to-plugin>', it will load whichever 'python3'
is in your $PATH. Probably what you want in most cases.

**Comment by sholderbach** [comment]
Good call!

**Comment by edhowland** [comment]
As mentioned above: PR1060 applies to this issue.. It appears to be linked so if merged this issue will get closed automagically.
