### ISSUE TITLE
Not showing definition description on custom command --help

### ISSUE THREAD

**Issue by stegrams** [nushell/nushell.github.io#110]
Based on [Documenting your command](https://www.nushell.sh/book/custom_commands.html#documenting-your-command), I can't create a top description on my custom commands.
In command line, when I press Enter my comment is simply ignored as expected, and in config.toml when I use multi-line comment ("""), still don't have it printed in my command --help.

 | # | name   | os version | kernel version |  
 | :---: | :--------: | :-------------: | :-----------------: |
 | 0 | Ubuntu | 20.04 | 5.8.0-44-generic | 

 version            | 0.28.0                                                                           
--- | ---
 short_commit       | 22ae962b                                                                         
 commit_hash        | 22ae962b573e1cd9cdf8db5c0278759132c3b6f3                                         
 commit_date        | 2021-03-09 10:40:17                                                              
 build_os           | linux-x86_64                                                                     
 rust_version       | rustc 1.50.0 (cb75ad5db 2021-02-10)                                              
 rust_channel       | stable-x86_64-unknown-linux-gnu (default)                                        
 cargo_version      | cargo 1.50.0 (f04e7fab7 2021-02-04)                                              
 pkg_version        | 0.28.0                                                                           
 build_time         | 2021-03-09 18:50:29                                                              
 build_rust_channel | release                                                                          
 features           | clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip  

PS: I restart nushell after each config.toml modification.

**Comment by filaretov** [comment]
Hey @stegrams, I just tried adding more documentation to a custom command like this:

```
# Greet a person
# 
# Specifically, say "hello" to the specified person.
def greet [
        name:string  # The person to greet
    ] {
    echo $"Hello, ($name)!"
}
```

And it worked:

```
> help greet
Greet a person

Specifically, say "hello" to the specified person.

Usage:
  > greet <$name> {flags}

Parameters:
  <$name> The person to greet

Flags:
  -h, --help: Display this help message
```

I also put it directly in config.toml like this:

```
startup = [
"""
# Greet a person
# 
# Specifically, say "hello" to the specified person.
def greet [
        name:string  # The person to greet
    ] {
    echo $"Hello, ($name)!"
}
"""
]
```

I hope this helps!

**Comment by stegrams** [comment]
> I hope this helps!

Basically, the upgrade to 0.36 helped a lot :wink:. 
I admit that I had forgotten how amazing this project is :+1:.

I put in config.toml your example on both versions and the bug has gone on the latest.

```
        Version 0.28.0                    |                Version 0.36.0
                                          |
> greet -h                                | > greet -h
Usage:                                    | Greet a person
  > greet <name> {flags}                  |
                                          | Specifically, say "hello" to the specified person.
Parameters:                               |
  <name> The person to greet              | Usage:
                                          |   > greet <$name> {flags}
Flags:                                    |
  -h, --help: Display this help message   | Parameters:
                                          |   <$name> The person to greet
                                          |
                                          | Flags:
                                          |  -h, --help: Display this help message
``` 
In command line, definition description is still ignored in both versions. 
Maybe it would be better if there was a way to enclose the custom command in to a pair of scope identifiers, e.g. brackets, in order to signal the REPL processor to wait until the custom command definition ends. And then, to assort the enclosing comments with the command as its documentation.

Though, after the new version, I think this issue, for the most part, is considered closed :wave:.

**Comment by filaretov** [comment]
Ah, I see, at least it's working now :smile: 

Questions like this tend to get answered more quickly on the Nu Discord, there's a link on the README on the [main repo](https://github.com/nushell/nushell).
