### ISSUE TITLE
lefthook does not work

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell.github.io#1116]
on the latest revision of the `main` branch, i get a lefthook error, even when committing an empty patch, even with `--no-verify`...

## reproduce
- `git checkout 7108e265`
- `git commit --allow-empty` gives *Error: required Lefthook version is higher than current*
- `git commit --allow-empty --no-verify` gives the same error

## expected
having steps for this in the `CONTRIBUTING.md` document would be great? :yum: 

maybe @hustcer you'll know about that? :innocent:

**Comment by hustcer** [comment]
Try to remove the node_modules folder and install again, it may help.

**Comment by hustcer** [comment]
Btw, it's better to upload a snapshot

**Comment by hustcer** [comment]
Just as the error says 'Error: required Lefthook version is higher than current', do `npm i` should work, whenever there is any update on `package.json` and `package-lock.json` a reinstall should be required
