### ISSUE TITLE
Contributor book doesn't have sidebar to navigate

### ISSUE THREAD

**Issue by bew** [nushell/nushell.github.io#1145]
Hello!

At https://www.nushell.sh/contributor-book/ and all subpages like https://www.nushell.sh/contributor-book/plugins.html there is no sidebar on the left like in the Nu book or the cookbook (lots of books ^^).

So when on these pages there is no way to see what other pages are available, or to navigate in the book 👀

**Comment by fdncred** [comment]
This is because the only page that's update in the contributor book is plugins.

**Comment by bew** [comment]
What about the other pages in that folder then?
https://github.com/nushell/nushell.github.io/tree/main/contributor-book
They are not part of the contributor book?

**Comment by fdncred** [comment]
I think they're part of the book, just not up to date. Some of them have been moved around in different parts of the book too.

**Comment by bew** [comment]
Oh, then maybe that contrib book's introduction should be removed, and move that plugin page in the book?

**Comment by sholderbach** [comment]
I started some work on the main repo in https://github.com/nushell/nushell/pull/11052 
Will clean house here soon.

**Comment by sholderbach** [comment]
Readded the sidebar in #1153
