### ISSUE TITLE
Document configuration setting for case-insensitive completions

### ISSUE THREAD

**Issue by ehdevries** [nushell/nushell.github.io#116]
### Problem

There is an existing configuration setting to enable case-insensitive completions ([source code](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/shell/completer.rs#L34-L48)):

```toml
[line_editor]
completion_match_method = "case-insensitive"
```

However, this setting is not currently documented on the [Configuration page of the Nu Book](https://github.com/nushell/nushell.github.io/blob/master/book/configuration.md#line-editor-section).

### Proposed solution

Add a row to the Line Editor section of the Configuration page - something like:

| Name                    | Purpose                                                                                  | Value Type | Options                                                                  |
|-------------------------|------------------------------------------------------------------------------------------|------------|--------------------------------------------------------------------------|
| completion_match_method | Enable case-insensitive completions; completions are case-sensitive by default          | string     | case-insensitive                                                         |

### Questions

The header of the Line Editor section currently reads:

> The `[line_editor]` section of the `config.toml` controls how our line editor, `rustyline` behaves. These configuration settings are specific to the `rustyline` crate we use.

The `completion_match_method` setting is not provided by `rustyline` - it's implemented directly by Nushell. Should the wording of the section header be changed, as well?

**Comment by eduardocanellas** [comment]
This setting was mistakenly placed on the root level configuration in the docs. I moved the line to the line editor table on #152.

**Comment by ehdevries** [comment]
Thanks so much!
