### ISSUE TITLE
Step value of range is not mentioned in document

### ISSUE THREAD

**Issue by kit494way** [nushell/nushell.github.io#1191]
Range can accept a step value like this

```nu
❯ 1..3..10
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 3 │
│ 2 │ 5 │
│ 3 │ 7 │
│ 4 │ 9 │
╰───┴───╯
```

But this is not documented.
https://github.com/nushell/nushell.github.io/blob/5954009c85289cb4e9e6d2d209da1f44a582ec13/book/types_of_data.md?plain=1#L156

**Comment by fdncred** [comment]
It should probably be in there, even though I don't like how it's implemented. The wording will have to be very precise because it's pretty different from what most people expect, which is more like `seq`.
```nushell
❯ seq 1 3 10 
╭───┬────╮
│ 0 │  1 │
│ 1 │  4 │
│ 2 │  7 │
│ 3 │ 10 │
╰───┴────╯
```
