### ISSUE TITLE
A page on control flow

### ISSUE THREAD

**Issue by TWSiO** [nushell/nushell.github.io#1207]
Looking through the book I didn't see anywhere that introduced `if` or most of the other control flow commands.

I suggest adding a page about control flow commands.

I think most people might not consider looking in the commands section about them since I think most people think of them as "part of the language" or more primitive "special forms" like range or the operators that wouldn't be included in the commands which people might be thinking of as "built in functions" (since I think control flow is presented separately in a lot of other languages as well). Plus it's also just helpful to gather up commands with similar use cases and letting people know what their names are so they don't have to go searching through the list of command names for the right command.

The page can also cover most of the error functionality mentioned in #772.

Here's a list of commands I could think to include.

- `if`
- `match`
  - At least a basic brief summary. Can point to the cookbook pattern matching page for more details.
- `for`
- `while`
- `loop`
- `break`
- `continue`
- `error make`
- `try`
- `return`

**Comment by fdncred** [comment]
sounds like a good idea.
