### ISSUE TITLE
Remove `$nothing` from document

### ISSUE THREAD

**Issue by kit494way** [nushell/nushell.github.io#1238]
`$nothing` has already been removed.
https://github.com/nushell/nushell/pull/10567

But `$nothing` is still used in some places.
- https://github.com/nushell/nushell.github.io/blob/2a0862ee6772a58d31b388db5fbb8d01e66c2a29/book/hooks.md?plain=1#L202
- https://github.com/nushell/nushell.github.io/blob/2a0862ee6772a58d31b388db5fbb8d01e66c2a29/book/types_of_data.md?plain=1#L483

**Comment by fdncred** [comment]
Agreed, it should be removed.
