### ISSUE TITLE
The Cookbook Setup page references the now-removed `env` command several times

### ISSUE THREAD

**Issue by NoahAndrews** [nushell/nushell.github.io#1289]
[Cookbook Setup](https://www.nushell.sh/cookbook/setup.html)

The `env` command was removed in [version 0.77](https://www.nushell.sh/blog/2023-03-14-nushell_0_77.html#breaking-changes). The Cookbook Setup page even refers to it as "new" in one place.

**Comment by fdncred** [comment]
Not surprised. It's difficult to keep the docs updated.
