### ISSUE TITLE
Something error syntax in zh-CN/README.md

### ISSUE THREAD

**Issue by volcaxiao** [nushell/nushell.github.io#1395]
When I read the documentation, this part didn't feel right.

<img width="737" alt="1715452772888" src="https://github.com/nushell/nushell.github.io/assets/92424372/f232b4b5-62b7-4193-8136-9fef0c4a10b1">

In [this file](https://github.com/nushell/nushell.github.io/blob/main/zh-CN/README.md), Maybe that's what you mean:

![image](https://github.com/nushell/nushell.github.io/assets/92424372/dbf1ba9b-1d40-4ac4-9eeb-0638edc983b4)

which are two ways to download.

**Comment by hustcer** [comment]
“Nushell is available as downloadable binaries, via your favourite package manager, in a GitHub Action, and as source code.” Have you read the English version? What do you think it should be translated to?

**Comment by volcaxiao** [comment]
> “Nushell is available as downloadable binaries, via your favourite package manager, in a GitHub Action, and as source code.” Have you read the English version? What do you think it should be translated to?

Yes, I have read the English version. I think "as downloadable binaries", "via your favourite package manager", "in a GitHub Action" and "as source code", there are four ways available. So, translation into Chinese should correspond to four sentences.

**Comment by hustcer** [comment]
@volcaxiao Thanks. I see your point and agree with it, PRs are always welcomed. The ZH translations is outdated toooo much
