### ISSUE TITLE
Dataframe page polars dtypes command fails

### ISSUE THREAD

**Issue by biscotty666** [nushell/nushell.github.io#1411]
The example `$df | polars dtypes` is given, which results in an error. Equivalent output can be generated with `$df | polars schema`.

**Comment by fdncred** [comment]
`polars dytpes` was removed in favor of `polars schema` on the latest main. Sounds like our docs are out of date again.

**Comment by NotTheDr01ds** [comment]
Looks like this was fixed (examples updated to `polars schema`) in #1414 and can be closed.
