### ISSUE TITLE
Query help page should mention it's a plugin

### ISSUE THREAD

**Issue by apraga** [nushell/nushell.github.io#1441]
Hi,

Would it be possible to add for `query`-* page (main, web, json, xml) that it's a plugin  (nu_plugin_query) ?
It would be easier to find for beginner.

If that's OK, I can contribute to the documentation. Thanks

**Comment by fdncred** [comment]
yes, but it would have to be changed in the rust code because the documentation for commands gets auto generated for the website from the commands when we make a release.

**Comment by apraga** [comment]
@fdncred Do you have any pointer where it's generated ? I could not find it easily. Thanks.

**Comment by fdncred** [comment]
@apraga I think the query plugins are in here https://github.com/nushell/nushell/tree/main/crates/nu_plugin_query

**Comment by apraga** [comment]
There are but, compared to the format plugin (which has a warning), I don’t see any obvious difference. I can open an issue on the main repo if that’s more helpful.
