### ISSUE TITLE
Table does quite line up on mobile

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell.github.io#15]
cc @Aloso who was working to improve this.

Looks like tables are a bit better, but not *quite* lined up, at least on my Samsung Galaxy S10.

Here's what it looks like for me:

![Screenshot_20191129-172703_Chrome](https://user-images.githubusercontent.com/547158/69843747-c28f7a80-12cd-11ea-934c-3d440ff09398.jpg)

**Comment by waldyrious** [comment]
Please refer to [this discussion](https://github.com/nushell/nushell.github.io/pull/13#discussion_r351905071) which has some context already.

**Comment by jonathandturner** [comment]
Are we ready to close this?

**Comment by Aloso** [comment]
@jonathandturner yes :+1:
