### ISSUE TITLE
are examples in a custom command documentation possible?

### ISSUE THREAD

**Issue by FrancescElies** [nushell/nushell.github.io#1504]
Is there a way to add examples in a custom command so that they are populated in the help as nushell does for native commands, e.g. `each`?

<img width="612" alt="grafik" src="https://github.com/user-attachments/assets/20b9bfcd-da42-4965-ad54-0865585ce4c6">

I checked the [docs](https://www.nushell.sh/book/custom_commands.html#documenting-your-command) but unless I missed it I couldn't see how to do that. 

I would like examples for custom commands to be selectable from the help.

**Comment by sholderbach** [comment]
Currently we don't have a mechanism for that, we don't do any special parsing of the doccomments.

Related issues on the main repo:

- https://github.com/nushell/nushell/issues/8851 
- https://github.com/nushell/nushell/issues/6878

**Comment by FrancescElies** [comment]
I searched but I guess I didn't use the right keywords, closing in favor of those ones
