### ISSUE TITLE
Commands provided by a plugin should appear in the Commands doc differently

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell.github.io#1515]
Currently [`inc`](https://www.nushell.sh/commands/docs/inc.html) appears without any indication that they require a plugin in order to work.  Probably need to modify the `make_docs.nu` to add something explaining this to the online-doc.

Edit: Looks like `make_docs` is already supposed to handle this, but it's not working for `inc` for some reason.

**Comment by fdncred** [comment]
It would be good to make it a part of the rust code so that make_docs.nu doesn't have to be updated every time we update a plugin. Like ayax just added plist to the formats plugin.

**Comment by NotTheDr01ds** [comment]
I'm not quite sure what you mean. In looking at the `plist` source, there's only a `usage` with no extra details there about it requiring a plugin, right?

I was thinking we could add something automatically since `make_docs.nu` can introspect whether or not a command is part of a plugin or not.  In fact, when I looked at [`from eml`](https://www.nushell.sh/commands/docs/from_eml.html#from-eml-for-formats) (and then confirming with a second glance at `make_docs.nu`, it appears that this is already implemented

It's just not working for `inc`.  That makes this a `made_docs.nu` bug, it appears. And probably something pretty easy to fix, so I'll take a stab at it.

**Comment by fdncred** [comment]
> ... h no extra details there about it requiring a plugin, right?

Right. I'm saying that we can put something in the plugins like a search term and then later use that in the make_docs script so that the make_docs script doesn't have to be hard coded. I just used plist as an example to show that our plugins continue to evolve.

**Comment by NotTheDr01ds** [comment]
@fdncred I understand what you're saying now.

I don't think we need to include anything like a search term, since `make_docs` can get this info from `plugin list` automatically.  Once I work past the other `make_docs` issues I've found, I'm planning on adding this so that *all* plugin commands include this warning automatically.
