### ISSUE TITLE
Document where/how to set `XDG_CONFIG_HOME`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell.github.io#1526]
Per https://discord.com/channels/601130461678272522/1278299991374565416

**Comment by NotTheDr01ds** [comment]
@ysthakur Thanks!  Related, I've just opened #1527 if you want to do that at the same time.

**Comment by ysthakur** [comment]
I'm not familiar with that one but sure, I can try to do both issues in one PR.

**Comment by NotTheDr01ds** [comment]
It's okay to punt on the other one if you want. I've played around with it a bit and can write it up, but I'll wait until after you land this one to avoid merge conflicts.
