### ISSUE TITLE
`datetime` type annotation is incorrect

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell.github.io#1547]
Don't have time to make the change at the moment (will later today), but as pointed out in [Discord today](https://discord.com/channels/601130461678272522/614593951969574961/1284037721194496043), the type annotation for `datetime` is incorrectly listed as `date`.

Easy fix - I'll update in a few; just a TODO reminder issue.

**Comment by sholderbach** [comment]
Result of the name discrepancy mentioned in:

- https://github.com/nushell/nushell/issues/9916
- https://github.com/nushell/nushell/issues/10332

Fixing this here is the right thing for now but we should address the root cause of this mess sooner rather than later.
