### ISSUE TITLE
Code blocks are scaled up too big on mobile

### ISSUE THREAD

**Issue by iFreilicht** [nushell/nushell.github.io#1575]
I'm reading the nushell book on iOS Firefox, and this is how the code blocks look:

![image](https://github.com/user-attachments/assets/94263671-3791-4944-81a4-11fe172d90f5)

The monospaced font is just way bigger than everything else, making the examples a bit tedious to read. Additionally, the line numbers don't line up at all, though this would be resolved by fixing #1573

**Comment by NotTheDr01ds** [comment]
There was a PR a while back to fix the mismatched numbers, but it might not have taken mobile into account.

I did notice when trying a local upgrade of the Vuepress components that the mismatch was fixed on desktop browser (and I had to revert the local commit).  Not sure about the block size, but that might also be changed on the latest Vuepress/Theme update.

**Comment by iFreilicht** [comment]
Ah, good to know! If you have a branch for me to test, please ping me, I'll be happy to take a look!

**Comment by iFreilicht** [comment]
Ah, one more thing I just noticed: Not all code blocks are scaled incorrectly. For example, on https://www.nushell.sh/book/cheat_sheet.html#strings, it looks like this:

![image](https://github.com/user-attachments/assets/a6924e86-bc96-4423-ab84-e5e75b788ad8)

**Comment by iFreilicht** [comment]
Yes, indeed! For posterity, this is what it looks like now:

![image](https://github.com/user-attachments/assets/4e2d2f2c-8382-4e75-bbe2-59cfe034aa81)
