### ISSUE TITLE
Document why `get` is strict and errors on blanks

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell.github.io#159]
originally from https://github.com/nushell/nushell/issues/3193

**Comment by NotTheDr01ds** [comment]
I believe this can be closed. The current behavior is now documented in the [`nothing` type](https://www.nushell.sh/lang-guide/chapters/types/basic_types/nothing.html#additional-language-notes) and also in [Navigating and Accessing Structured Data - Handling Missing Data](https://www.nushell.sh/book/navigating_structured_data.html#handling-missing-data), which is that;

* A *missing* value is different than a `null`/`nothing` value
* `get` will error on a *missing* value
* `get` will not error when a result has a `null`
* `default` can be used to convert both *missing` and `nothing` values to another value
* The optional operator `?` can be used to return a `null` in place of a missing value
