### ISSUE TITLE
Style Guide - Spaces between brackets and lists/records?

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell.github.io#1603]
The [Best Practices](https://nushell.sh/book/style_guide.html) (a.k.a. Style Guide) chapter of the Nushell Book includes recommendations for Nushell code that is contributed to official Nushell repositories (e.g., [nu_scripts](/nushell/nu_scripts).

As mentioned in the first paragraph:

> as for now it is still work in progress and subject to change. We welcome discussion and contributions.

On the weekly call today, we agreed that we need to more actively reach out for community feedback on certain areas, with a Nushell issue (such as this one) being decided on as the way the community can "vote" most easily.

Short lists and records in Nushell (those displayed on a single line) can have several forms:

```nu
[item1 item2 item3]
[ item1 item2 item3 ]
{a: 5, b: 10}
{ a: 5, b: 10 }
```

Should there be a space after/before opening and closing brackets?  Or do we care?

Please vote on your bracket-spacing preference below by selecting the Thumbs-Up emoji on your preferred option below.

![image](https://github.com/user-attachments/assets/70cf4a3f-9da4-4ba8-bdc7-d03f76f2b917)

Comments are welcome as well.

**Comment by NotTheDr01ds** [comment]
No space:

```nu
[item1 item2 item3]
[a: 5, b: 10}
```

**Comment by NotTheDr01ds** [comment]
Single-space:

```nu
[ item1 item2 item3 ]
{ a:5, b: 10 }
```

**Comment by NotTheDr01ds** [comment]
Option 3:  We shouldn't enforce a common style for this.  It is okay if some code uses one form, and other code in the same module/repo uses the other.

**Comment by WindSoilder** [comment]
I think there is one more form for list:
```
[item1, item2, item3]
```
Actually this is what I preferred.

**Comment by NotTheDr01ds** [comment]
Right - I should have mentioned that commas-or-not will probably be a separate discussion.

**Comment by NotTheDr01ds** [comment]
So:

Option 4 - Space and commas in lists:

```nu
[ item1, item2, item3 ]
{ a:5, b: 10 }
```

**Comment by NotTheDr01ds** [comment]
Option 5 - No-space and commands in lists:

```nu
So:

Option 4 - Space and commas in lists:

```nu
[item1, item2, item3]
{a:5, b: 10}
```

**Comment by fdncred** [comment]
it would be great if the record example was consistent. `a:5` vs `b: 10`

**Comment by NotTheDr01ds** [comment]
@fdncred Thanks - I'm probably going to make that mistake at least once in my edits to the actual style guide as well.  Lots of copy/paste of "correct" and "incorrect" versions and I'm certain to miss at least one (probably more).

But I don't feel too bad - The current style guide has a lot of inconsistencies already ;-)
