### ISSUE TITLE
Update Shells in Shells for 0.99 / 0.100

### ISSUE THREAD

**Issue by catwell** [nushell/nushell.github.io#1632]
[Shell in Shells](https://github.com/nushell/nushell.github.io/blob/37c713b23ef420430949f32a145d1a7803ba7298/book/shells_in_shells.md) should be updated now that [`std/dirs` is not loaded on startup](https://www.nushell.sh/blog/2024-11-12-nushell_0_100_0.html#removals-toc).

**Comment by NotTheDr01ds** [comment]
Thanks!  I've updated the chapter.  And apologies for the delay on this one!
