### ISSUE TITLE
Use `--locked` flag for Cargo install

### ISSUE THREAD

**Issue by allan2** [nushell/nushell.github.io#1641]
Omitting the `--locked` flag can cause installation to fail when dependencies have broken updates. 

For example, trying to install the 0.100.0 release using `cargo install nu` fails for me due to an issue with uutils.

I suggest adding the `--locked` flag to all `cargo install` references in the docs. I'd be happy to open a PR.

**Comment by fdncred** [comment]
There's only been a couple times over the last 5 years that --locked has been required. However, I don't see any harm to adding it.

**Comment by stifskere** [comment]
That just happened to me yesterday, so I upvote this.

**Comment by fdncred** [comment]
Yup, now is one of the couple times this has happened due to changes at uutils/coreutils.
