### ISSUE TITLE
404 of sample code in Nu book

### ISSUE THREAD

**Issue by PegasusPlusUS** [nushell/nushell.github.io#1650]
Introduction -> Getting Started, first code sample, :(
In Quick Tour:
book/quick_tour.md

https://github.com/nushell/nushell.github.io/blob/main/book/@snippets/introduction/ls_example.sh

**Comment by PegasusPlusUS** [comment]
It seems ALL code samples in the book are missing!

**Comment by fdncred** [comment]
I thought they were all in the md now. What exactly is missing?
![image](https://github.com/user-attachments/assets/2d2a8639-e3df-499e-b8c0-34f0d8c7576d)

**Comment by PegasusPlusUS** [comment]
I can only see @code tag, no actual code, click on the tag will get 404 page:
![Screenshot 2024-11-27 115832](https://github.com/user-attachments/assets/d4e689b2-a2f6-42fc-bac8-887c101218d4)
![Screenshot 2024-11-27 115852](https://github.com/user-attachments/assets/d0022552-6109-492d-83d0-26004a2515b9)

**Comment by fdncred** [comment]
maybe @NotTheDr01ds understands what's going on?

**Comment by hustcer** [comment]
@PegasusPlusUS It's not a bug, It's a `vuepress` code snippet syntax that cannot be recognized by Github (and it shouldn't) but can correctly handled by Vuepress, you should read the docs from https://www.nushell.sh/book/quick_tour.html rather than github repo
