### ISSUE TITLE
allow wider pages

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell.github.io#1661]
Is it possible to decrease the width of the areas marked in red? I'd like to have less wasted space and see more of the information.
![Screenshot 2024-12-04 134545](https://github.com/user-attachments/assets/0939d284-d9b5-453b-ad58-ea9636d9c7fb)

**Comment by NotTheDr01ds** [comment]
Good question - I've noticed that as well from time to time.

The answer is ... "probably"?  ;-)

I'll try to look into it, unless @hustcer knows more readily.  I'm sure it involves CSS changes.

Might be tricky to get "just right" across platforms.  I'm definitely no CSS guru, so not sure.

**Comment by fdncred** [comment]
I manually hacked mine by turning off this css setting in the red oval. We could also change it to something like `width: 90%` if we wanted some padding. But I really have no idea how to do that without hacking.

![image](https://github.com/user-attachments/assets/efe4f785-0e6a-41e7-a3ec-5d2de0ba12b2)

**Comment by fdncred** [comment]
Some quick research

https://github.com/vuejs/vuepress/issues/1867

**Comment by fdncred** [comment]
It seems like it's width = 50%. I'd like to see it at least width = 85%

**Comment by hustcer** [comment]
> It seems like it's width = 50%. I'd like to see it at least width = 85%

That's too wide. It's about `740px` currently, I can change it to around `960px` (at most 1060px), that's the width of our homepage: https://www.nushell.sh/ or the width of the content area of https://docusaurus.io/docs

**Comment by fdncred** [comment]
I'm not sure how hard coding it to a px really helps. Is px relative to something or just pixels? People can have ultra-wide monitors, and it will be filled with white space on both sides. That's not super helpful. Seems like a percentage is better so that it works for people with all different shapes of monitors.

**Comment by hustcer** [comment]
@fdncred I have a clear grasp of what you're thinking，and it's quit easy to fix. However, I disagree with the idea. Space make sense and space make better reading experience. That's why all SSG tools like vuepress, vitepress, hugo, docusaurus, rspress, astro won't use 85% etc. as the default value for their page layout. Let's see what copilot says:

![Screenshot 2024-12-06 at 15 16 10](https://github.com/user-attachments/assets/f40c2c6c-2fe1-436d-984c-03baeb3d8a9c)

**Comment by hustcer** [comment]
> Thanks @hustcer for discussing this with me. I'm up for trying 1000-ish and seeing how it looks. I still think a % would be better but I'm happy to defer to you and your expertise and try out what you suggest to make it better.

It's deployed

**Comment by fdncred** [comment]
Definitely better than it was. Notice the boxes have 3 lines vs 5 now and the red boxes are not quite as big. Thanks for working on this.
![image](https://github.com/user-attachments/assets/7e14820c-65ec-4eb0-b377-853efa6ebb9f)
