### ISSUE TITLE
Broken link: `Escaping to system`

### ISSUE THREAD

**Issue by PRO-2684** [nushell/nushell.github.io#1664]
In [this page](https://www.nushell.sh/book/moving_around.html#filesystem-commands), at the bottom of the "NOTE" section:

> See [Escaping to system](https://www.nushell.sh/book/escaping.html#escaping-to-the-system) for details.

The link is broken.

**Comment by NotTheDr01ds** [comment]
Thanks! For some reason that didn't get caught by the auto-checker when I updated.
