### ISSUE TITLE
config nu --doc doesn't exist

### ISSUE THREAD

**Issue by yanis-fourel** [nushell/nushell.github.io#1710]
In the page https://www.nushell.sh/book/configuration.html#quickstart
It says:

> Add commands to this file that should run each time Nushell starts. A good first example might be the buffer_editor setting above.
> You can find a detailed list of available settings using:
> ```nu
>  config nu --doc | nu-highlight | less -R
>  ```
> 

However when I run it I get

```
> config nu --doc | nu-highlight | less -R
Error: nu::parser::unknown_flag

  × The `config nu` command doesn't have flag `doc`.
   ╭─[entry #4:1:12]
 1 │  config nu --doc | nu-highlight | less -R
   ·            ──┬──
   ·              ╰── unknown flag
   ╰────
  help: Available flags: --help(-h), --default(-d). Use `--help` for more information.
```

Same thing with

> To view a simplified version of this documentation from inside Nushell, run:
> ```nu
> config env --doc | nu-highlight | less -R
> ```

after the TOC

It probably doesn't exist anymore.

**Comment by hustcer** [comment]
Make sure you are using the latest nu: v0.101

**Comment by NotTheDr01ds** [comment]
@yanis-fourel Right - Sometimes the docs are a little behind, but in this case the Config chapter was updated for the latest release since there were some major changes to the way config works in 0.101.  See [the Blog post](https://www.nushell.sh/blog/2024-12-04-configuration_preview.html) for details.

**Comment by NotTheDr01ds** [comment]
> Same thing with
> 
> > To view a simplified version of this documentation from inside Nushell, run:
> > ```nu
> > config env --doc | nu-highlight | less -R
> > ```
> 
> after the TOC

Oops!  That one is wrong.  It never existed (other than in development code) in the first place.  I'll fix that.

**Comment by NotTheDr01ds** [comment]
Yeah - I deleted the wrong one when trimming it down.  Thanks for the catch!
