### ISSUE TITLE
Document the pathvar command

### ISSUE THREAD

**Issue by nathom** [nushell/nushell.github.io#174]
Some of the info in `Coming from bash` page and the `Adding paths to your PATH` page needs to be updated to include `pathvar`.

**Comment by NotTheDr01ds** [comment]
I think this can be closed - While the original `pathvar` is obsolete, the "Coming from Bash" chapter now includes:

```
$env.PATH = ($env.PATH | append /usr/other/bin)
```

And there's a more in-depth discussion in the [Configuration](http://localhost:8080/book/configuration.html#path-configuration) chapter.
