### ISSUE TITLE
Provide more examples for `str` commands

### ISSUE THREAD

**Issue by Tauheed-Elahee** [nushell/nushell.github.io#181]
The `str` commands are documented in the [command_reference page](https://www.nushell.sh/book/command_reference.html) starting here [https://www.nushell.sh/book/command_reference.html#str-camel-case](https://www.nushell.sh/book/command_reference.html#str-camel-case). There are simple examples on how to use it, with the only ones being documented are `echo "sample text" | str command` several of these commands list `...args` as "...args: optionally *command* by column paths". There are no examples showing how one uses the optional arguments and how to use the command on structured data.

This issue was made because I wanted to list and then delete file names containing a substring I had tried the following.
`ls | str contains 'old'`
`str contains 'old' ls.name`
`ls | get name | str contains 'old'`
however, none of the solutions above worked. This is an example of using structured data and I don't know how to approach it.

**Comment by Tauheed-Elahee** [comment]
I found the solution to my particular problem:
`ls -a | where name =~ "old" | each {echo $it.name}`

As documented here: [https://www.nushell.sh/book/commands/where.html#where-with-comparison](https://www.nushell.sh/book/commands/where.html#where-with-comparison)

It'd still be nice to have documentation on the `str` commands though.

**Comment by NotTheDr01ds** [comment]
While "more" is always a possibility, I think that this can be reasonably closed with:

* [String Type](https://www.nushell.sh/book/types_of_data.html#strings) linking to ...
  * [Working with Strings](https://www.nushell.sh/book/working_with_strings.html), which includes a section on some of the [`str` subcommands](https://www.nushell.sh/book/working_with_strings.html#the-str-command)
  *  [Handling Strings](https://www.nushell.sh/book/loading_data.html#handling-strings) in the "Loading Data" chapter
