### ISSUE TITLE
Command reference shortcomings

### ISSUE THREAD

**Issue by Bellarmine-Head** [nushell/nushell.github.io#185]
What would really help me with getting into Nu is having any easy reference to all the commands.

This should be the place: https://www.nushell.sh/book/command_reference.html

But this page has some issues:-

1) There's no index to each command at the top of the page.  A section at the top with each command listed, and linked to the relevant section further down the page would be great.  There could be multiple command names per line; it doesn't have to be a big, long vertical list.
2) Scroll down a bit to the first command: `alias`.  There is no anchor link to this command!  I can't bookmark a link to it.  This makes building a commands index hard, of course.
3) There is an anchor link to the command's examples: https://www.nushell.sh/book/command_reference.html#examples  But the trouble with this is that *every* command's `Examples` section has the exact same link!  Scroll to the bottom of the page, and click on the `for` command's `Examples` anchor link (when the green `#` appears).  You will be taken to the top of the page, to the *first instance* of what this link links to.
4) Ditto for each command's for `Usage`, `Parameters`, `Flags`.
5) It would be okay for each command to have links to its  `Examples`, `Usage`, `Parameters`, `Flags` sections, so long as the links were specialized by the command name.
6) What are `str camel-case` and `for` doing at the bottom of the page, and not in alpahbetical order like the others?
7) Incidentally, `str camel-case` is an outlier (along with a few others) in that it has a repeated title, and the second one has an associated anchor link.
8) All in-document links don't quite work correctly, in that clicking on them takes you to that section (e.g. "Flags"), but the heading (e.g.  "Flags") is scolled off the top of the frame, so you're not quite sure what you're looking at.  You have to scroll up a bit to check.

**Comment by filaretov** [comment]
Would it be possible and desirable to create the command reference from the `--help` output of each command? That is already fairly verbose and very helpful, and tends to be the most up-to-date documentation of each command.

**Comment by rgwood** [comment]
@Bellarmine-Head Thanks for the detailed issue. The command reference was previously just all the individual command pages concatenated; it certainly had a lot of shortcomings. I recently converted it to a much more compact table with links; I think this addresses your points but feel free to reopen this if you still have issues with the page.

@filaretov Yep! That's essentially how the command pages are generated: https://github.com/nushell/nushell.github.io/blob/8e90bac68f26d4ddf099a909e2042709d61c56ac/book/make_docs.nu

**Comment by Bellarmine-Head** [comment]
@rgwood - so much better; thanks!
