### ISSUE TITLE
Improve documentation on strings

### ISSUE THREAD

**Issue by filaretov** [nushell/nushell.github.io#191]
The current section on strings in the "Types of data" page could use some additions.

There are two existing issues that seem related to this:

- #127, documenting the `char` command
- #181, providing more examples for `str`

Both of these commands are commonly used with strings.

It seems to me that working with strings is a major part of a shell, should a top-level page about strings be created? It could contain the following topics:

- Strings, quoted, bare, string interpolation
- The `char` command
- The `str` command
- References to other relevant sections, such as "Loading data"

The current section on strings in "Types of data" could redirect the reader to the top-level page.

I'm interested in working on this.

**Comment by rgwood** [comment]
@filaretov There is a top-level page for strings now: https://www.nushell.sh/book/strings.html

**Comment by filaretov** [comment]
The link seems to be https://www.nushell.sh/book/working_with_strings.html

That's great, thanks!
