### ISSUE TITLE
Nu Book should have a section about strings

### ISSUE THREAD

**Issue by adzubla** [nushell/nushell.github.io#204]
I was learning nu shell using Nu Book and noticed that documentation specific to strings is missing.

Nu Book should have a section about strings: "Working with strings" or "Working with text"
There are some examples of it but they are all scattered in topics about other subjects.

The idea is to show how nu could be used instead of sed/awk to do text processing.

Suggested topics:

- trim
- upper/lower case
- substrings
- spliting
- string compare
- regex matches and groups
- parsing
- type conversion to/from strings
- ansi colors

**Comment by rgwood** [comment]
@adzubla I think this addresses your request: https://www.nushell.sh/book/strings.html

**Comment by Dan-Gamin** [comment]
[There is already a page for it.](https://www.nushell.sh/book/working_with_strings.html)

But it doesn't cover all the things @adzubla mentioned.

**Comment by Dan-Gamin** [comment]
I'm working on PR right now.

**Comment by adzubla** [comment]
Thanks, the documentation is way better now!

I'm note sure if its the right forum to ask but...
When using tab completion on a name which contains spaces, nu replaces with the name in backticks (acute char) like this:

![Captura de tela 2022-06-05 024716](https://user-images.githubusercontent.com/9607562/172037302-b05355f7-1a32-4b7b-9824-76c74d82ece4.png)

What is this? It is not mentioned anywhere...

**Comment by Dan-Gamin** [comment]
@adzubla I have never seen that before. I have no idea.
