### ISSUE TITLE
Move the books onto nushell.sh?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell.github.io#22]
Right now we're publishing the Nu book through gitbooks, but we could look into publishing it differently, and also pull in the contributor book and cookbook.

**Comment by sebastian-xyz** [comment]
If we want to build the books using Jekyll, we could use [jekyll-gitbook](https://github.com/sighingnow/jekyll-gitbook) as our base and adpat it to fit the other designs.

**Comment by jonathandturner** [comment]
Sounds good. We could try it on one repo and see how it goes
