### ISSUE TITLE
Document possible types accepted in signatures

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell.github.io#223]
When making a custom command (e.g., `def foo [x: <some-type>] { })`, it's not clear which types are accepted in the signature. We should put into the book which values of `<some-type>` are accepted.

The accepted values are in the source code here: https://github.com/nushell/nushell/blob/c2bad7112358c472406d23dd95403f3f610a048f/crates/nu-parser/src/parser.rs#L2008

**Comment by pedromfedricci** [comment]
The accepted types are listed under the [Parameter types]( https://www.nushell.sh/book/custom_commands.html#parameter-types) section, but the list is not up to date. Maybe make this issue about updating them?

**Comment by pedromfedricci** [comment]
If so: #580.

**Comment by kubouch** [comment]
You're right, it's already document but out-of-date.
