### ISSUE TITLE
Overview of documents status?

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell.github.io#239]
I think we need to create a table to summarize the status of all the documents, so that we can translate the ones that are completed and relatively stable. Maybe a table like this:
| name               | status| zh-cn| ja       |
| ------------------ | ------- | ------- | -------------- |
|aliases.md             | Finished| Translated     | Untranslated   |
| configuration.md           | In progress     |   Being translated by @xyz | Untranslated   |

**Comment by jntrnr** [comment]
I love this idea. Should we keep it as an issue or make it part of the book?

**Comment by hustcer** [comment]
> I love this idea. Should we keep it as an issue or make it part of the book?

Maybe as an issue first, then become part of the book if necessary?

**Comment by hustcer** [comment]
I will create a table later
