### ISSUE TITLE
feedback: cmd+f "install" on homepage comes up empty

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell.github.io#24]
Going to https://www.nushell.sh/ and searching for "install" came up empty. The top nav bar also doesn't include a link to "download". It's only now that after opening up this issue that I'm seeing the "get" link.

I think I was thrown off by the big green "blog" button, which feels like the main call to action in the navigation menu but didn't point me to what I wanted.

The reason why I'm bringing this up is because just like when logging in on a website I'll search for "login" on the page, when installing software I'll be looking for "install" on the page. Hope this is useful feedback!

**Comment by sebastian-xyz** [comment]
These are 2 ideas I came up with
1) This one expands a little popup menu containing the other links when '⌄' is clicked 
![Nushell_navbar_new](https://user-images.githubusercontent.com/52786998/72002683-2e0f2500-3248-11ea-8b69-2c6a1413f54e.png)
![Nushell_navbar_new_exp](https://user-images.githubusercontent.com/52786998/72002684-2ea7bb80-3248-11ea-9d61-d88bd267ab54.png)



2) This one is more like the layout of the books with a sidemenu opening when the 'hamburger' is pressed
![Nushell_navbar_new_alternative](https://user-images.githubusercontent.com/52786998/72000761-4715d700-3244-11ea-80cb-5f773f0206d2.png)
![Nushell_navbar_new_alternative_exp](https://user-images.githubusercontent.com/52786998/72000972-b390d600-3244-11ea-8846-c8f4ec927b99.png)

@yoshuawuyts @jonathandturner what do you think about it? Any other suggestions or improvements?

**Comment by jonathandturner** [comment]
One option might be to have the "Download Nushell" button, and not to have an Install or Get and keep the headers we have now. Would that work?

I think having it on the button makes it feel more like a call to action.

**Comment by jonathandturner** [comment]
I also wonder if we should have a block of "how to install" on the main page towards the top. We could put it in a separate color so it's easier to notice.

Sites like http://www.typescriptlang.org/ have both the Download button and a section of how to install it a little later on the main page. Maybe we could do something like that?

**Comment by yoshuawuyts** [comment]
I like the idea of having a clear call to action to "install/download" right at the top, and then a more elaborate section somewhere else on the page. I think typescript nails the priorities in that regard, as people visiting the page will likely want to do one of 3 things:

- find out what the project is about
- install the project
- figure out how to do a particular thing (which usually means referencing the docs)

The first screen people see captures *all* of this. I think this caters nicely to people with different knowledge levels about the project, and makes the main page really useful!

![Screenshot 2020-01-09 01 38 36](https://user-images.githubusercontent.com/2467194/72027859-d04aff00-3280-11ea-83a0-3ce7ad1170f8.png)

**Comment by sebastian-xyz** [comment]
Yes it that worked. I had to reduce the font size on mobile devices by 1px. But I think that didn't reduce the readability that much.

![Nushell_navbar_new](https://user-images.githubusercontent.com/52786998/72087602-059b2f80-3309-11ea-86be-0c017319abe5.png)

How it looks on mobiles:
![Nushell_navbar_new_mobile](https://user-images.githubusercontent.com/52786998/72087613-0c29a700-3309-11ea-9b6a-455af3a1f4e2.png)

**Comment by sebastian-xyz** [comment]
> 
> 
> I also wonder if we should have a block of "how to install" on the main page towards the top. We could put it in a separate color so it's easier to notice.
> 
> Sites like http://www.typescriptlang.org/ have both the Download button and a section of how to install it a little later on the main page. Maybe we could do something like that?

That seems like a nice thing to add. 

Maybe with that section added we should delete the Installation page on the website so we don't have to keep 3 different guides to install Nu up to date. 

Or we could use links like https://www.nushell.sh/installation.html#installing-from-cratesio to refer to the correct section on the Installation page.

**Comment by ibraheemdev** [comment]
I think this can be closed now that we have the new site.

**Comment by ibraheemdev** [comment]
I think this can be closed now that the site has been updated.
