### ISSUE TITLE
Correct Winget installation instructions

### ISSUE THREAD

**Issue by dgalbraith** [nushell/nushell.github.io#246]
The instructions to install `nushell` using [Winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) reference an incorrect package name `nu`.

The correct package name is `nushell` - the website and book documentation should be updated to reflect this.

**Comment by jntrnr** [comment]
@dgalbraith would you mind sending a PR to change this? we've seen some changes with how the winget package works, but it's maintained by a third-party rather than by us
