### ISSUE TITLE
break up command_reference

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell.github.io#278]
Our new search engine, Algolia, doesn't like massive pages. I don't really blame it. It would be nice to break up the command reference page into alphabetical pages so that these results could be found by searching.

Like:
a.md/html -> alias, all? ansi, any? append
b.md/html -> benchmark, build-string
etc

![image](https://user-images.githubusercontent.com/343840/157901272-e6df5097-3148-4c0a-98f2-580ef61f7802.png)

apparently this requires some type of scripting because this is what the command_reference.md looks like
```
# Command Reference

<div v-for="command in $site.pages.filter(p => p.path.indexOf('/book/commands/') >= 0)">
   <h1><code>{{ command.title }}</code></h1>
   <Content :page-key="command.key"/>
</div>
```

**Comment by rgwood** [comment]
@fdncred As an alternate solution, what if we just change the command reference page to have less content?

Right now it seems to merge _everything_ including examples from every individual command page into 1 monster page. I think the reference page would be more readable if it skipped examples and had a table with links to each individual command (and maybe a short description of each). That would solve the Algolia problems too.

**Comment by fdncred** [comment]
I think I'd like to keep examples on the command page, since I think examples are more important than text most of the time. As far as having a reference page with links to commands, that's kind of what I'm suggesting above. My suggestion was just to order that reference page alphabetically with links to the `a` commands and `b` commands etc. I'm open to other organization strategies though. I just want to make the page smaller so it can be ingested by the crawler.

**Comment by rgwood** [comment]
Hmm. I should have been more clear. Right now we have:

1. Individual command pages (ex: [`ls`](https://www.nushell.sh/book/commands/ls.html), [`where`](https://www.nushell.sh/book/commands/where.html))
2. [The huge command reference page](https://www.nushell.sh/book/command_reference.html) which just concatenates the content of every individual command page

I'm thinking we change the command reference page to be much more succinct, with links to the individual command pages. The individual command pages would still contain examples.

> My suggestion was just to order that reference page alphabetically with links to the a commands and b commands etc.

I might have misunderstood the initial proposal - it sounded like you also wanted to split the existing reference page into multiple pages. Which is doable but I think it would be simpler to keep it as 1 page.

**Comment by fdncred** [comment]
I'm fine with combining our suggestions somehow but I'd rather not have 300+ individual pages for the commands, which is why i was trying to group them by first letter of the command.

**Comment by rgwood** [comment]
I see. Possibly dumb question: what's wrong with an individual page for each command? Personally I like having an individual page for each command (easy to generate, easy to link to).

**Comment by fdncred** [comment]
I think it's too cumbersome to have hundreds of tiny files. Another thought is to organize them by category, like if you did `$nu.scope.commands | select command category` but if you wanted an accurate list, you'd have to filter some things out. for me, that command returns 411 commands - lol.
