### ISSUE TITLE
PowerShell && and ||

### ISSUE THREAD

**Issue by PDQDakota** [nushell/nushell.github.io#288]
In the [operator map](https://github.com/nushell/nushell.github.io/blob/b8c550cfa7e902f22e7dc244674aa031ebea169a/book/nushell_operator_map.md) page, PowerShell is listed as only supporting `-and` and `-or` for `&&` and `||`

As of [PowerShell 7.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70) the `&&` and `||` operators are supported, is the operator page intended to reflect only Windows PowerShell or would it be prudent of me to submit a PR to add the new operators to the PowerShell column?

**Comment by rgwood** [comment]
Good catch! I don't think the operator map page is intended to reflect a specific PowerShell version; feel free to submit a PR.
