### ISSUE TITLE
Cargo flags on installation page are wrong

### ISSUE THREAD

**Issue by nespera** [nushell/nushell.github.io#29]
On the installation page it says to run `cargo install nu --all --features=stable` for an "all bells and whistles" install. But it seems there is no `--all` flag in cargo. I'm new to Rust so not sure if this should be `--all-features` or `--features=stable` which both seem valid.
EDIT: I have copied the installation instructions from the book

**Comment by waldyrious** [comment]
> I have copied the installation instructions from the book

[The book](https://www.nushell.sh/book/en/installation.html) still needs to be fixed, btw — the [installation page](https://github.com/nushell/book/blob/master/en/installation.md) still contains the outdated instructions.

@sebastian-xyz why isn't there a link to the book from the main website? I'd expect it to be in the menu at the top, for example.

**Comment by sebastian-xyz** [comment]
@waldyrious Yes we should definitely put it in a more visible place than in the documentation section. I would like to update the main page but I've pretty limited time at the moment. I hope I can get into this by next week. We discussed in #24 some things we want to improve. In addition to those improvements we could also make a small section about the book so people can find it easily.
