### ISSUE TITLE
Colors need better contrast for accessibility

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell.github.io#3]
We should do a pass over the site with something like https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf?hl=en and update the colors to have better contrast. I did a quick one and noticed a few aren't quite high enough for clear readability.

**Comment by sebastian-xyz** [comment]
Should we close this one too?

**Comment by jonathandturner** [comment]
Yes, we should be good

**Comment by jonathandturner** [comment]
by the way, I did end up making the font just slightly bigger. I think it helps with readability (for me at least)
