### ISSUE TITLE
Render quotation blocks with more emphasis

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell.github.io#365]
If you look at any page with quotation block, like for example https://www.nushell.sh/book/line_editor.html#configuration, you will see that the blocks are rendered in a grayed out fashion. It happened to me several times that I unconsciously missed some of those blocks even though they contained critical information to me. I know that this is mildly subjective, but if it hurts the documentation readability for me then I'm probably not the only one, as a rule of thumb.

Can we improve the rendering of these blocks? Perhaps they should not be quotation blocks even? Since they are not quotations, but rather important remarks.

**Comment by fdncred** [comment]
This is what I see. Is it what you're talking about?

<img width="786" alt="Screen Shot 2022-04-03 at 6 54 21 AM" src="https://user-images.githubusercontent.com/343840/161426747-d741d847-748d-4dce-b1ff-88896b4c38ff.png">

<img width="785" alt="Screen Shot 2022-04-03 at 6 54 30 AM" src="https://user-images.githubusercontent.com/343840/161426752-fc141da9-2a97-4797-a310-f2897746848e.png">

**Comment by chtenb** [comment]
No, I'm referring to these

![image](https://user-images.githubusercontent.com/1030961/161429998-f0d02e72-eb81-49fa-bb7e-66824d6a33a1.png)

**Comment by fdncred** [comment]
ok. I see what you mean. I use the dark reader extension so I usually don't see white backgrounds unless I turn it off. This is what I see.
<img width="798" alt="Screen Shot 2022-04-03 at 8 44 47 AM" src="https://user-images.githubusercontent.com/343840/161431041-8b483f85-9f49-438d-9555-d70ef9a3f28d.png">

I'm wondering if this is a css setting in the vuepress stuff we could change?

**Comment by fdncred** [comment]
so that thing is called a `blockquote`. I don't see a way to change that but I'm not vuepress person either. Maybe we could change `>` to tips `:::` like this?

<img width="779" alt="Screen Shot 2022-04-03 at 8 56 43 AM" src="https://user-images.githubusercontent.com/343840/161431502-e305cf07-3ff9-498e-95a2-a95ff68cb1e6.png">

if you want to submit a PR with changing these to tips we can see what it looks like.

**Comment by chtenb** [comment]
Yeah, that looks very appropriate imho.

> if you want to submit a PR with changing these to tips we can see what it looks like.

I'll have a look into this
