### ISSUE TITLE
Improve documentation on file paths

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell.github.io#371]
Relevant page: https://www.nushell.sh/book/types_of_data.html#file-paths

In particular it is unclear how the path type differs from the string type, and what "platform-independent" *exactly* means.
Since working with paths is so fundamental to shell scripting I think this deserves a thorough treatment.

**Comment by fdncred** [comment]
That documentation may be left over from v0.44.0 since in that version `FilePath`s were a thing. Now they're not even a type.

From crates/nu-protocol/src/ty.rs
```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Type {
    Int,
    Float,
    Range,
    Bool,
    String,
    Block,
    CellPath,
    Duration,
    Date,
    Filesize,
    List(Box<Type>),
    Number,
    Nothing,
    Record(Vec<(String, Type)>),
    Table,
    ListStream,
    Unknown,
    Error,
    Binary,
    Custom,
    Signature,
}
```

**Comment by chtenb** [comment]
@fdncred I think this was closed prematurely. The docs still mention filepaths as a dedicated data type.

**Comment by fdncred** [comment]
I just submitted a PR to remove them
