### ISSUE TITLE
Publish binaries via Chocolatey too

### ISSUE THREAD

**Issue by biocomp** [nushell/nushell.github.io#38]
It's a package manager for windows, which I like to use to install apps: https://chocolatey.org. Unfortunately, I have never published something there myself, so don't know how to do that.

**Comment by mhmdanas** [comment]
This repo is for Nu's website; it is not the place for requests for Nu itself. Can somebody transfer this issue to https://github.com/nushell/nushell if it isn't already there?

**Comment by sebastian-xyz** [comment]
Available via chocolatey and installation instructions are also provided on the website. Closing.
