### ISSUE TITLE
Two pages with the same title

### ISSUE THREAD

**Issue by adzubla** [nushell/nushell.github.io#405]
In "Nu Book" there are two pages with the same title, which is a little confusing:

- Nu Fundamentals > Loading Data > Working with strings
- Nu Fundamentals > Working with strings

I sugest changing the page in Loading Data to "handling strings" or "parsing strings".

**Comment by adzubla** [comment]
![Captura de tela 2022-04-16 141440](https://user-images.githubusercontent.com/9607562/163684843-585eda5c-3aa9-4bad-9a6c-005eb2b0455a.png)

**Comment by fdncred** [comment]
Feel free to change the names to differentiate.
