### ISSUE TITLE
Contributor book is outdated

### ISSUE THREAD

**Issue by Kangaxx-0** [nushell/nushell.github.io#409]
I am new to nushell, is the contributor book outdated? I got quite confused and had to look into the source code to figure it out, e.g - [Vaules](https://github.com/nushell/nushell.github.io/blob/main/contributor-book/values.md) says something like below 

`pub struct Value {
    pub value: UntaggedValue,
    pub tag: Tag,
}`

However, the implementation was completely changed

<img width="670" alt="image" src="https://user-images.githubusercontent.com/85712372/164108081-8d6f864a-06b4-4da0-a053-27d30c53d0ff.png">

Is this correct? Is there any other documentation for someone like me who is new to nushell, but wants to make contributions?

**Comment by jntrnr** [comment]
@Kangaxx-0 - yeah it still needs to be updated. We hid it from the main page until we had time to fix it. At this point, it probably needs to be re-written since so much changed with the new engine that came with 0.60

**Comment by Kangaxx-0** [comment]
@jntrnr Thanks, that makes sense
