### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Dan-Gamin** [nushell/nushell.github.io#431]
Can we please have a dark mode? It doesnt have to be anything fancy. Just a CSS `@media` query using `prefers-color-scheme: dark` to make the website dark would work.

**Comment by Dan-Gamin** [comment]
I realize this is a duplicate of #122 .

**Comment by rgwood** [comment]
PRs are welcome.

In the long term we might be moving to VuePress v2 or VitePress and I think that might give us dark mode for free. But that's probably a while away (and it will require a lot of effort).

**Comment by fdncred** [comment]
I think vuepress 1.0 doesn't support it but 2.0 does. we just need a friendly voluteer to upgrade us. :)
