### ISSUE TITLE
The Search Bar doesnt work.

### ISSUE THREAD

**Issue by Dan-Gamin** [nushell/nushell.github.io#432]
_No Description Needed for this issue_

**Comment by rgwood** [comment]
> No Description Needed for this issue

This does need a description, unfortunately; what exactly isn't working for you? What OS+browser are you using?

The search bar works for me on Linux+Firefox:
![image](https://user-images.githubusercontent.com/26268125/166827255-0a287e44-c71a-407e-bb6d-c7ae0b0538bc.png)

**Comment by Dan-Gamin** [comment]
> > No Description Needed for this issue
> 
> This does need a description, unfortunately; what exactly isn't working for you? What OS+browser are you using?
> 
> The search bar works for me on Linux+Firefox: ![image](https://user-images.githubusercontent.com/26268125/166827255-0a287e44-c71a-407e-bb6d-c7ae0b0538bc.png)

wait it works now? huh... i swear it was broken earlier. weird
