### ISSUE TITLE
Support the naked domain name

### ISSUE THREAD

**Issue by brettcannon** [nushell/nushell.github.io#46]
When I type `nushell.sh` (at  least in Firefox on macOS Catalina), the page seems to end up sitting there waiting for a response. But if I type `www.nushell.sh` I get an instant response. My guess  is the DNS records for `nushell.sh` weren't set up for  a naked domain to either forward to `www` or to serve the same response as `www`.

**Comment by jonathandturner** [comment]
I'm on Firefox 75.0 in Windows, and `nushell.sh` redirects to `https://www.nushell.sh/`.  I wonder if it's a macOS or Firefox version-specific thing. What version of Firefox are you using?

**Comment by waldyrious** [comment]
FWIW, `nushell.sh` works for me in Firefox 75.0 on macOS Catalina.

**Comment by brettcannon** [comment]
I will assume it was some weird glitch on my machine or my DNS resolver. Sorry about the noise, everyone!
