### ISSUE TITLE
Document how to read/check an environment variable more explicitly

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell.github.io#464]
https://www.nushell.sh/book/environment.html contains several ways on how to set environment variables and reads them in the code in some places but does not explictly mention how to read them with `$env.VARIABLE` or `env`. 

Add a section "Reading environment variables"

Inspired by nushell/nushell#5684

**Comment by jgollenz** [comment]
If this is still up for grabs, I'd like to do it
