### ISSUE TITLE
Landing page refresh

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell.github.io#49]
nushell is gaining momentum, and I think it's time for our landing page to get a refresh. Let's modernize it, highlighting nushell's great features, and just making nushell really shine 🌟 

Some ideas:
- Modern layout (less mouse interaction, more vertical scrolling)
- Highlight key features in an image/text side by side layout. For example: 
![slack screen shot](https://user-images.githubusercontent.com/833576/82158408-b6847e80-9855-11ea-95e5-c3a4ae313d3b.png) (source: https://slack.com/intl/en-ca/lp/three)
- Maybe a softer colour palette? The high contrast may be befitting of an odler shell, but this is nushell 🙂
- Unroll the tabular installation instructions into something really concise. For example: ![starship screen shot](https://user-images.githubusercontent.com/833576/82158443-e469c300-9855-11ea-829a-ae44184b0efa.png) (source: https://starship.rs/)
- More tasteful borders, fewer horizontal rules (and the ones we do have should be lower contrast).

**Comment by jonathandturner** [comment]
Some great ideas there.

I like the links you mention. Taking a look at them, the pages feel very clean and clear, so that you want to keep learning more.

CC @sebastian-xyz who did our original page.

**Comment by jonathandturner** [comment]
Here's the starship landing paged, too:

![image](https://user-images.githubusercontent.com/547158/82158475-3e14d080-98dc-11ea-8517-ba9fdc8f9913.png)

Just thought I'd put it here to help generate ideas

**Comment by thegedge** [comment]
Yeah, that's a good inspiration. I would love an end result that is clean, and streamlined for vertical navigation.

**Comment by sebastian-xyz** [comment]
I totally agree. The current design isn't that intuitive.
I think a good way to move forward could be to create a new channel in our discord so we can include more people in the discussion for the new design.

**Comment by jonathandturner** [comment]
Sounds great. I'll do that.

**Comment by jonathandturner** [comment]
I've added #new-website-design on [discord](https://discord.gg/NtAbbGn)

**Comment by fdncred** [comment]
wow, this is old. we've refreshed a few times since this one. lol

**Comment by jntrnr** [comment]
@fdncred would be nice to follow some of the ideas in the original post. We don't currently show a lot of the main reasons yours want to use Nushell
