### ISSUE TITLE
README is broken

### ISSUE THREAD

**Issue by merelymyself** [nushell/nushell.github.io#510]
The README currently has many images that are not loading due to not being present.

![image](https://user-images.githubusercontent.com/88221256/174290983-3d220eb9-4937-439b-8303-07b3c624b42d.png)

**Comment by fdncred** [comment]
I was looking at these start with `/frontpage`. I wonder how long that folder has been missing?

**Comment by fdncred** [comment]
Looks like they never worked? This is the first commit from @rgwood  that I see them in https://github.com/nushell/nushell.github.io/tree/ba0b28666e1ac58bb7aafff268af55acdc98f5f7

**Comment by hustcer** [comment]
They work well in the home page: https://www.nushell.sh/

**Comment by rgwood** [comment]
Yeah I think the README’s primary purpose is to be the front page for the website. Maybe there’s a way to change that but I haven’t looked into it, PRs welcome.

**Comment by hustcer** [comment]
Fixed by https://github.com/nushell/nushell.github.io/pull/518
