### ISSUE TITLE
Pressing Enter on the documentation search result is broken

### ISSUE THREAD

**Issue by shift-d** [nushell/nushell.github.io#551]
# How to reproduce:
1. Open website 
2. `<Ctrl-K>`
3. Type some query (PATH, for example)
4. Press `<Enter>`

# Result:
You are being redirected to the broken link: `https://www.nushell.sh/https:%2F%2Fwww.nushell.sh%2Fbook%2Fcommands%2Fpath.html`.
It seems that documentation search somehow appends the documentation link to the website domain.

# Expected behavior:
Same steps to reproduce, but instead of pressing `<Enter>` just click with mouse on the result. You will be redirected to the correct link.

**Comment by fdncred** [comment]
i was able to reproduce it - looks like the url is getting messed up somehow on enter.

**Comment by hustcer** [comment]
It's a @vuepress/plugin-docsearch bug reported: https://github.com/vuepress/vuepress-next/issues/1024
