### ISSUE TITLE
The overlay section of the book appears out of date.

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell.github.io#564]
Hello there :wave: :yum: 

i was reading the [overlay chapter](https://www.nushell.sh/book/overlays.html#preserving-definitions) and i noticed something strange :confused: 

The book is talking about `overlay add --prefix` in ["Prefixed Overlays"](https://www.nushell.sh/book/overlays.html#prefixed-overlays) and about `overlay remove --keep` in ["Preserving definitions"](https://www.nushell.sh/book/overlays.html#preserving-definitions), but none of these flags appear to exist in the `nu` sub commands of the `overlay` command :open_mouth: 

maybe the book or the commands are out of sync?
just to let you know :wink: 

## Additional context
```rust
$ nu --version
0.66.2
```

**Comment by kubouch** [comment]
The newest version is 0.67 and was released yesterday. That has the --prefix flag.

The --keep flag needs to be updated, I forgot about that.

**Comment by amtoine** [comment]
> The newest version is 0.67 and was released yesterday. That has the --prefix flag.
> 
i forgot to update my system... :eyes: 
i can see the `--prefix` flag now in 0.67 :star_struck: 

> The --keep flag needs to be updated, I forgot about that.
>
got it :yum:

**Comment by kubouch** [comment]
The `--keep` flag still needs to be updated. If someone wants to update it, please go ahead.

**Comment by amtoine** [comment]
> The `--keep` flag still needs to be updated. If someone wants to update it, please go ahead.
>
is the update about changing `--keep` to `--keep-custom` in the book page? :yum: 
that's the flag in the `overlay remove` command that seems to do the same as `--keep` in the book :+1:

**Comment by kubouch** [comment]
Yeah, that. And also mention the new `--keep-env` flag.

**Comment by amtoine** [comment]
i can propose something if that's a go for you :yum:

**Comment by kubouch** [comment]
Yeah, sure, go ahead!

**Comment by amtoine** [comment]
cool :+1:

**Comment by amtoine** [comment]
this issue might have been closed with #565, right? :yum:

**Comment by kubouch** [comment]
Yeah, true.
