### ISSUE TITLE
command name string clarification

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell.github.io#566]
The custom commands section states

> In Nushell, a command name is a string of characters or a quoted string.

However this description may be misinterpreted as saying that commands can be called with a (possibly quoted) string as the command name, e.g. `ls | "my subcommand"`. Maybe it would be good to clarify here, or later in the custom commands section, that while commands can be defined with quoted-string names, they cannot be called that way.

**Comment by fdncred** [comment]
I think this means that when defining a custom command you can do it like this.

```
def some_command [] { }
```
or with quotes
```
def "some command" [] {}
```

That's my guess.

**Comment by Zoybean** [comment]
Ah, apologies. That much was already clear to me. I'm just suggesting that the documentation could be improved so that it is no longer ambiguous to other readers.

**Comment by fdncred** [comment]
ya, sure. unambiguous documentation is the goal. :)
