### ISSUE TITLE
Html links to md files in book

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell.github.io#575]
The page-tree on the left on https://www.nushell.sh/book/ (english!) redirects to (not existing) `.md` files instead of `.html`

I never worked with vuepress, but i suspect it might have to do with specifying file extensions in [the config.js](https://github.com/nushell/nushell.github.io/blob/main/.vuepress/config.js) since the cookbook, german-version, etc work just fine.

**Comment by hustcer** [comment]
That's the way it works，does it break anything？

**Comment by petrisch** [comment]
@Jan9103 The links are pointing to `.md` files, however for me they work. So I see what you mean, but I don't know either where this can lead to problems.

**Comment by hustcer** [comment]
@Jan9103 Do you still have this issue now? It works fine for me

**Comment by fdncred** [comment]
I didn't think those `md` files existed anywhere but on the repo. I thought when the website is built, it's built as a static website and only html is generated. So, if you wanted the markdown files, I believe you'd have to get them from the repo like this `fetch https://raw.githubusercontent.com/nushell/nushell.github.io/main/book/3rdpartyprompts.md`. 

Am I wrong about this?

**Comment by hustcer** [comment]
> yes, but the issue is, that the html page links to md files (which as you already said dont exist)

It doesn't matter at all, although the href may link to a md like:
```html
<a href="/book/getting_started.md" class="sidebar-item sidebar-heading active" aria-label="Getting Started"> Getting Started </a>
```
However when you click the nav menu it will automatically redirect to https://www.nushell.sh/book/getting_started.html for me

**Comment by hustcer** [comment]
BTW, if it fails sometimes guess that's due to some js hasn't been fully loaded and executed, just refresh and try again.
