### ISSUE TITLE
Potential for order-by / sort-by confusion

### ISSUE THREAD

**Issue by robations** [nushell/nushell.github.io#578]
`order-by` (database), `sort-by` (filters) and `sort-by` (lazyframe) are essentially synonyms, but in nushell are used in different contexts.

I suggest adding a note ("See also") to each page to indicate the difference between the two (three) commands.

Order-by returns a confusing error message in the wrong context and users may be otherwise unaware that `sort-by` also exists.

This would also help with the overloaded sort-by:

https://www.nushell.sh/book/commands/sort-by.html
https://www.nushell.sh/book/commands/_sort-by.html

Both are findable through the search dialog, but it wasn't immediately obvious that there are actually two separate doc pages with the same name.

<img width="275" alt="search sort" src="https://user-images.githubusercontent.com/205320/186923642-78677f51-921d-4d7f-9881-29e6f1e3e7d7.png">

(Happy to suggest changes via PR, though as a non-expert would only attempt if requested.)

**Comment by hustcer** [comment]
This issue should be resolved now
