### ISSUE TITLE
Improve documentation for def/custom command definition

### ISSUE THREAD

**Issue by generic-github-user** [nushell/nushell.github.io#593]
Some of the examples from the [page on custom commands](https://www.nushell.sh/book/custom_commands.html) may be worth adapting to help provide more comprehensive usage information in the documentation on the [`def`](https://www.nushell.sh/book/commands/def.html) statement; particularly those covering subcommand definitions, parameter types, default parameter values, etc. The command description itself and parameter information could probably also be made more thorough. I'll put together a PR to this effect and you can decide whether it would be beneficial to integrate into the documentation.

**Comment by NotTheDr01ds** [comment]
Looks like this can be closed - It was for the `def` command and according to the PR was moved over to the main repo.  Regardless, I think the `def` doc is much improved in this area.
