### ISSUE TITLE
`from csv` doc shows wrong output for `--headerless`

### ISSUE THREAD

**Issue by mrec** [nushell/nushell.github.io#60]
https://www.nushell.sh/commands/from-csv.html

I'd expect `--headerless` to mean "there's no header row, treat the first row as data". Testing in the web demo supports that expectation. In the sample output shown on the doc page, though, it's not only discarded the first (header) row completely, but also discarded the first data row too.

**Comment by rgwood** [comment]
I think this can be closed; `from csv` now uses `--noheaders` and the docs no longer show output.

 https://www.nushell.sh/book/commands/from_csv.html

**Comment by hustcer** [comment]
@rgwood Thanks
