### ISSUE TITLE
CORS preventing JQuery from loading, quick-docs fail to work

### ISSUE THREAD

**Issue by cathalgarvey** [nushell/nushell.github.io#61]
As in title: I'm getting an error where CORS blocks JQuery so I can't browse the quick reference docs for the built-in commands. :/

**Comment by jzaefferer** [comment]
@cathalgarvey could you provide a screenshot or the exact error message? From DevTools console or network tab? A bit more detail would help a lot.

**Comment by jzaefferer** [comment]
Maybe related: https://www.nushell.sh/demo/ fails to load for me in Firefox, since it blocks Sentry from loading. Which causes the whole demo to fail, and the error isn't tracked.

In my case, the blocking is caused by a browser extension, uBlock origin. Without it, the demo works fine.

**Comment by cathalgarvey** [comment]
Sorry, missed the first request for info. I collected screenshots of the network and console panes which show that it's been blocked for CORS reasons, and the subsequent errors because `$` is not defined.

I'm also using self-defence extensions including uMatrix, but I've already allowlisted JQuery in that plugin and checked the others for issues. The error messages appear to make it clear that it's caused by CORS.

![nushell_docs_fail_console](https://user-images.githubusercontent.com/1167837/92460945-8411df00-f1c0-11ea-8c40-45d2144500c6.png)
![nushell_docs_fail_networkpane](https://user-images.githubusercontent.com/1167837/92460953-883dfc80-f1c0-11ea-92d7-f759c65132d2.png)

**Comment by ibraheemdev** [comment]
I think this can be closed now that we have the new site.

**Comment by rgwood** [comment]
@cathalgarvey Thanks for reporting this and sorry for the very late reply. Closed as the website's been revamped and I don't think this will be an issue anymore. Feel free to comment here or open a new issue if you can still reproduce this.
