### ISSUE TITLE
Asking Windows users to download Visual Studio Community Edition is inappropriate

### ISSUE THREAD

**Issue by jamiedgh** [nushell/nushell.github.io#63]
From [https://www.nushell.sh/book/en/installation.html](https://www.nushell.sh/book/en/installation.html):

> For Rust to work properly, you’ll need to have a compatible compiler suite installed on your system. These are the recommended compiler suites:
> . . .
> . . .
> . Windows: Visual Studio Community Edition
> For Windows, when you install Visual Studio Community Edition, make sure to install the “C++ build tools” as what we need is link.exe which is provided as part of that optional install. With that, we’re ready to move to the next step.

Keep in mind that Visual Studio Community Edition with just the C++ build tools (unless I'm doing it incorrectly) is a **10.4 GB** installation! I'll stick with Vim, thanks.

Since I used scoop.sh to install nu, I already have gcc installed. I'll see if I can just stick with that, but I would recommend that your directions remove such a big ask. It runs very counter to the entire philosophy of nu advertised on the website to ask newcomers to get such a massive dependency.

**Comment by jonathandturner** [comment]
@JamieGhassibi - It may just be better to point people to the official Rust instructions rather than coming up with our own as gcc also isn't an option for some users. We'd end up duplicating what they have.
