### ISSUE TITLE
Documentation: code snippets could be syntax-highlighted

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell.github.io#639]
### Related problem

Consider as an example something like [Elvish's documentation](https://elv.sh/learn/tour.html#value-pipelines). There, the code snippets are syntax-highlighted in HTML to better aid reading comprehension.

### Describe the solution you'd like

If you can hook up a basic syntax-highlighting method, lining up with nushell's language, to whatever you use to generate the docs, that'd definitely spruce things up.

**Comment by fdncred** [comment]
I'm wondering if we could do something like `some | pipe | line | nu-highlight | to html` to get some better syntax highlighting in markdown. I'm not sure html is even supported?

**Comment by fdncred** [comment]
closed by https://github.com/nushell/nushell.github.io/pull/1078
