### ISSUE TITLE
Documentation: backtick strings should be mentioned in the string section

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell.github.io#640]
### Describe the bug

I was going to suggest adding backtick strings (from JS), but apparently they already exist, and moreover seem to function the same as single-quotes except with the advantage that you can include single-quote characters inside them (which I believe is impossible for single-quote strings without interpolation). So, they deserve a mention.

Also, this is just an opinion of mine, but I think they should be considered the "idiomatic" non-escaped string over the single-quote kind, which means they are used in examples from now on in place of single-quotes. Single-quote strings can remain as a slightly-less-convenient alternative for people who expect that syntax to "just work".

### How to reproduce

n/a

### Expected behavior

n/a

### Configuration

n/a

**Comment by sholderbach** [comment]
Feel free to add a respective section on them to the string literal section.
I think making them the idiomatic string is ill advised as they are not transferring expectations from shells and most programming languages that use quotes. Furthermore on many European keyboards backticks are deadkeys to support the accent grave and thus require two separate keypresses.

**Comment by fdncred** [comment]
I've been documenting quotes with an eye towards changing how they work because I think we can probably handle quotes better. You can find this documentation [here](https://hackmd.io/yBEUx4czTMuHcTICt-xZAA?view).
