### ISSUE TITLE
Invalid octal binary literals

### ISSUE THREAD

**Issue by thara** [nushell/nushell.github.io#670]
I found invalid octal binary literals `0o[777]`In [Binary data section in Types of Data page](https://www.nushell.sh/book/types_of_data.html#binary-data).

actual result in Nu 0.68.1 is below:

```
> 0o[777]
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #297:1:1]
 1 │ 0o[777]
   · ───┬───
   ·    ╰── did you mean 'col'?
   ╰────
  help: No such file or directory (os error 2)
```

It seems to the parser restricts values by radix for parsing binary literals.
(On the other hand, octal integer literals is not restricted by radix)
https://github.com/nushell/nushell/blob/c1105e945e40f3cb24f429fae8d215f024f3a48b/crates/nu-parser/src/parser.rs#L1160

It should be correct literals such like `0o[377]`.

---

I tried to make a PR for fixing the problem, but the commit hook auto-format entire the file and contains changes i didn't intend.
https://github.com/nushell/nushell.github.io/compare/main...thara:nushell.github.io:fix_invalid_octal_binary_literal?expand=1

Should I make a PR containing these changes or avoid them by some way?

**Comment by sholderbach** [comment]
Thanks for catching that.
Might be worth opening an issue on nushell to add a helpful error message when exceeding `0o[377]`.

Didn't even know that pre-commit hook existed.
I went ahead and split that up.
