### ISSUE TITLE
Please add the FreeBSD port/pachage to the installation instructions page

### ISSUE THREAD

**Issue by yurivict** [nushell/nushell.github.io#728]
### Describe the bug

[here](https://www.nushell.sh/book/installation.html)

### How to reproduce

n/a

### Expected behavior

n/a

### Configuration

n/a

**Comment by sholderbach** [comment]
Can you refer us to the FreeBSD package source that distributes nushell? Feel free to open a PR with instructions directly as the FreeBSD experience among the core maintainer team is limited.

**Comment by yurivict** [comment]
* [port's commit](https://cgit.freebsd.org/ports/tree/shells/nushell)
* [FreshPorts page](https://www.freshports.org/shells/nushell/)

**Comment by rgwood** [comment]
Thanks for porting Nushell!

The FreeBSD port is included in the Repology list on that page:

![image](https://user-images.githubusercontent.com/26268125/210423914-7fcddd9d-6da3-498a-a5ba-d8aca38e3f6d.png)

I think that's sufficient - we need to keep the documentation succinct and we can't mention every port/package individually.
