### ISSUE TITLE
a dead link on the plugins page

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell.github.io#741]
i think the following link is dead in the website:
- https://book.nushell.sh/en/plugins

i was looking at the [plugins page](https://www.nushell.sh/blog/2019-08-23-introducing-nushell.html#plugins) and the first link, "_plugins chapter_", does not give any result :open_mouth: 

cheers :wave: :yum:

**Comment by amtoine** [comment]
looks like the correct page should be https://www.nushell.sh/contributor-book/plugins.html, right? :wink:

**Comment by amtoine** [comment]
if that's correct, i'd be happy to help and create a PR to close this issue :relieved:

**Comment by fdncred** [comment]
That link you found in the contributors book is very old and mostly not applicable since it's from nushell 0.44.0 and before. It would be great to get the contributors book up and online again.

**Comment by amtoine** [comment]
> That link you found in the contributors book is very old and mostly not applicable since it's from nushell 0.44.0 and before. It would be great to get the contributors book up and online again.
>
oooh so it's not supposed to be online right now? :open_mouth: 
i found it by searching for "_plugins_" in the search engine of the book :thinking: 

none of the other links i found in my 2nd comment are correct for this? :confused:

**Comment by fdncred** [comment]
correct. if it were supposed to be available we'd have a link to it on nushell.sh. We used to have that but removed that link so people don't stumble upon it. I'm not sure how to make the algolia search ignore it.

**Comment by amtoine** [comment]
> correct. if it were supposed to be available we'd have a link to it on nushell.sh. We used to have that but removed that link so people don't stumble upon it. I'm not sure how to make the algolia search ignore it.
>
actually this link appears in the available pages directly :thinking: 

it's in 
> Nu can't come with everything you might want to do with it, so we're releasing Nu with the ability to extend it with plugins. There's more information in the plugins chapters. Nu will look for these plugins in your path, and load them up on startup.
>
in the first paragraph of ["Plugins"](https://www.nushell.sh/blog/2019-08-23-introducing-nushell.html#plugins)

this link should probably be removed with what you say, shouldn't it? :open_mouth:

**Comment by fdncred** [comment]
right. what i meant was that it doesn't show up here any longer. this is where it used to be.
![image](https://user-images.githubusercontent.com/343840/212487437-bcd50bb2-50f1-429a-b16c-3dda2960e0ea.png)


yes, it should be removed.

**Comment by amtoine** [comment]
> right. what i meant was that it doesn't show up here any longer. this is where it used to be. ![image](https://user-images.githubusercontent.com/343840/212487437-bcd50bb2-50f1-429a-b16c-3dda2960e0ea.png)
> 
oh yes, that would make sense, this is exactly why i was confused :scream: 

> yes, it should be removed.
>
i can handle that if you wish :yum:

**Comment by fdncred** [comment]
> i can handle that if you wish

sure, if you have time. no rush.
