### ISSUE TITLE
add a link to the default config file in the `explore` page

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell.github.io#742]
first of all, thank you so much for the documentation about `explore`, i've been looking forward to seing it and now that it's here, `explore` can become a truly powerfull tool :star_struck: 

i was reading the [`explore` page](https://www.nushell.sh/book/explore.html) and i think the `default-config.nu` string in the ["Config" paragraph](https://www.nushell.sh/book/explore.html#config) could link to the true default config file, either
- https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu
- or even https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L321 to go onto `explore` directly

cheers :tada: 

PS: again, i'd be happy to help and open a PR for this :relieved:

**Comment by fdncred** [comment]
I was going to say the 2nd link would be good to add but the config file changes so often that i'll quickly be pointing to the wrong line. So, the first link to the file itself is probably more durable. I'd land a commit for this. Thanks!

**Comment by amtoine** [comment]
> I was going to say the 2nd link would be good to add but the config file changes so often that i'll quickly be pointing to the wrong line. So, the first link to the file itself is probably more durable.
>
yeah, sadly...
i mentionned it because it would be the best i think, but of course it might very well change so the other permanent (? at least more) link should be the way to go :relieved: 

>  I'd land a commit for this. Thanks!
>
already some changes applied??
man you're fast :open_mouth:

**Comment by amtoine** [comment]
i can not see any commit about this issue :thinking: 
am i missing something? :yum:

**Comment by fdncred** [comment]
has there been a pr to fix it yet?

**Comment by amtoine** [comment]
> has there been a pr to fix it yet?
>
no i don't think so!

> I'd land a commit for this
>
i thought you did it, didn't you? :open_mouth: 

my bad, i might have misunderstood :laughing: 
i can do it if you wish :wink:

**Comment by fdncred** [comment]
Just a misunderstanding. No worries. Yes, please do a PR.

**Comment by amtoine** [comment]
> Just a misunderstanding. No worries. Yes, please do a PR.
>
i'm in! :muscle:
