### ISSUE TITLE
[zh-CN] fix statement about lines output type

### ISSUE THREAD

**Issue by das-g** [nushell/nushell.github.io#768]
In [ 加载数据→处理字符串](https://www.nushell.sh/zh-CN/book/loading_data.html#%E5%A4%84%E7%90%86%E5%AD%97%E7%AC%A6%E4%B8%B2) after

> ```
> > open people.txt | lines
> ───┬──────────────────────────────
>  0 │ Octavia | Butler | Writer
>  1 │ Bob | Ross | Painter
>  2 │ Antonio | Vivaldi | Composer
> ───┴──────────────────────────────
> ```

the prose claims
> 可以看到，我们正在处理这些行，因为我们又回到了一个表中。

However, `lines` yields a `list`, not a `table` as that sentence might imply. (See PR #764 for a fix of the same problem in English and German.)

**Comment by das-g** [comment]
Are you sure this has been completed? [The concerning line](https://github.com/nushell/nushell.github.io/blob/main/zh-CN/book/loading_data.md?plain=1#L93) looks unchanged on `main`:
https://github.com/nushell/nushell.github.io/blob/ac3d54d740ab470326388f0fee14d7911d28d0e1/zh-CN/book/loading_data.md#L93

**Comment by hustcer** [comment]
Sorry, I thought you had fixed it

**Comment by das-g** [comment]
> Sorry, I thought you had fixed it

I've only fixed the analogous problem in languages I know well enough to do so somewhat confidently. I don't know any Chinese or Japanese, but was with the help of Google translate able to at least determine, that the problem might be present in these translations, too, thus I filed this issue and #767.
