### ISSUE TITLE
Variables and Subexpressions section has outdated information

### ISSUE THREAD

**Issue by jangler** [nushell/nushell.github.io#797]
https://www.nushell.sh/book/variables_and_subexpressions.html

> There are two types of evaluation expressions in Nushell: variables and subexpressions. You know that you're looking at an evaluation expression because it begins with a dollar sign ($). This indicates that when Nushell gets the value in this position, it will need to run an evaluation step to process the expression and then use the resulting value. Both evaluation expression forms support a simple form and a 'path' form for working with more complex data.

Only variables begin with `$`, subexpressions dropped the `$` in version 0.32, according to this page.

**Comment by fdncred** [comment]
Docs probably need to be updated. It's a constant fight to keep them current.

**Comment by Kissaki** [comment]
The "variables and subexpressions" page no longer exists. The [Variables page](https://www.nushell.sh/book/variables.html) does not mention subexpressions. I don't see a specific page about subepxressions. Operators does not list it as a described operator, [but lists it in the order anyway](https://www.nushell.sh/book/operators.html#order-of-operations).

It seems to me this ticket can safely be closed without further action.

**Comment by NotTheDr01ds** [comment]
Agree with @Kissaki - This can be closed.
