### ISSUE TITLE
interaction of nushell with screen readers?

### ISSUE THREAD

**Issue by RichMorin** [nushell/nushell.github.io#817]
Screen readers, as used by the blind, can navigate HTML tables. However, some of the other things you're doing with display formatting would likely be inaccessible. Please consider setting up (and testing!) an generally accessible display format.

**Comment by rgwood** [comment]
Thanks for the issue.

> some of the other things you're doing with display formatting would likely be inaccessible

Do you have specific examples?

**Comment by RichMorin** [comment]
I haven't actually played with nushell; just looked at your web page. However, one thing I spotted (FYI, I'm sighted) was an error diagnostic with all sorts of cool-looking graphics. I'm pretty sure that a screen reader would not be able to make sense of this.

You might want to post some messages on mailing lists for the blind, dyslexic, and/or visually disabled. If you'll send me a note (rdm@cfcl.com), I can try to find some prospects...

**Comment by rgwood** [comment]
Let us know if you find specific examples of accessibility concerns.
