### ISSUE TITLE
Missing screenshots on front page

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell.github.io#819]
I get this
![image](https://user-images.githubusercontent.com/343840/224595365-6f628aea-e9e7-4ddd-9ee1-45ddca0c0f73.png)

and looking in dev tools it shows this
![image](https://user-images.githubusercontent.com/343840/224595336-dfaa652d-089e-491f-aa0e-9addf9aadd86.png)

If I change to InPrivate mode, it seems to load fine.

Confused 🤔

**Comment by hustcer** [comment]
It works fine for me. It will be better if we can upload the images to OSS or something the like

**Comment by fdncred** [comment]
I'm not sure what is going on. It looks fine on Windows MS Edge, MacOS Safari, InPrivate MS Edge on MacOS, but it pukes on Edge on MacOS. It just seems to me that ERR_TOO_MANY_REDIRECTS wouldn't be a local issue, but I could be wrong.

**Comment by NotTheDr01ds** [comment]
Assuming this is no longer an issue?
