### ISSUE TITLE
Make `each` easier to find.

### ISSUE THREAD

**Issue by Ryan-McLemon** [nushell/nushell.github.io#84]
When trying to find an analog for a Bash `for`, I searched for `for`, `loop`, and `iteration` in the Nushell docs, but came up short ... can we add something to make it a bit easier to find `each`?

**Comment by NotTheDr01ds** [comment]
This has been implemented and should be closeable - *"for"*, *"loop'*, and *"iterate"* are all search terms for `each` now:

```nu
help -f iterate
```

Returns - `each`, `each while`, and `items`.

I'll also add a mapping in the "Coming from Bash" chapter of the book in a few minutes, but even without that, I'd call this one "done", right?
