### ISSUE TITLE
Invalid example for passing values as command parameters

### ISSUE THREAD

**Issue by vmario** [nushell/nushell.github.io#841]
On https://www.nushell.sh/book/coming_from_bash.html you have the command `ls **/Makefile | get name | vim $in`. It doesn't work because pipeline sends data to standard input and vim returns an error.

```
/tmp/test> ls **/Makefile | get name | vim $in                                                                                                                                       
Vim: Warning: input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
```

You can use `vim (ls **/Makefile | get name)`. Moreover, there is also a similar problem with the original bash command. Vim doesn't cooperate well with `xargs` too. For bash example you should use Neovim:

```bash
find . -name Makefile | xargs nvim
```

or simply use dedicated find's option:

```bash
find . -name Makefile -exec vim {} +
```

**Comment by NotTheDr01ds** [comment]
This has been resolved at some point (not by the commit above, which, unless I'm wrong, referenced the wrong issue).  The commands now use the spread operator with Vim and work correctly.
