### ISSUE TITLE
doc env command is not found

### ISSUE THREAD

**Issue by zeromake** [nushell/nushell.github.io#842]
> system: `Windows_NT  10.0 19044 x86_64 MS/Windows`
> nushell: [release](https://github.com/nushell/nushell/releases/download/0.77.1/nu-0.77.1-x86_64-pc-windows-msvc.zip)

[env doc](https://www.nushell.sh/commands/docs/env.html)

```sh
> env
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #27:1:1]
 1 │ env
   · ─┬─
   ·  ╰── executable was not found
   ╰────
  help: program not found
> which env
>
```

**Comment by WindSoilder** [comment]
Hi, it's removed on the latest version, you can use `$env` instead

**Comment by zeromake** [comment]
@WindSoilder 
Thanks for the answer.

**Comment by rgwood** [comment]
We should remove `env` and any other outdated commands from the website, let's leave this open until that gets fixed.

**Comment by voiceroy** [comment]
Here's an outdated command I found in [the docs](https://www.nushell.sh/book/configuration.html#configuring-nu-as-a-login-shell)

```
> env | each { |it| echo $"let-env ($it.name) = '($it.raw)'" } | str join (char nl)
```

**Comment by fdncred** [comment]
This works for me, but it uses and external env command.
```
^env | lines | split column '=' key val | each {|r| echo $"let-env ($r.key) = '($r.val)'"} | str join (char nl)
```
This is close and uses `$env` but it's not quite the same. You'd have to do some filtering to remove the closures and record env vars.
```
$env | transpose key val | each {|r| echo $"let-env ($r.key) = '($r.val)'"} | str join (char nl)
```

**Comment by hustcer** [comment]
Fixed

**Comment by tayopi** [comment]
There is still documentation that lists the `env` command.
![image](https://github.com/nushell/nushell.github.io/assets/2684768/85483762-cd83-44e2-aa30-18b986763ce6)

**Comment by fdncred** [comment]
`env` hasn't been a command for a while, it needs to be removed if anyone is up for creating a PR.
