### ISSUE TITLE
RSS/Atom feed?

### ISSUE THREAD

**Issue by lambdagolem** [nushell/nushell.github.io#85]
I just wanted to ask if there is support/if it would be possible to add support for RSS or atom on the blog? The old blog had support for that I think. I understand that this is probably rather niche and not a priority for the project if it is possible.

**Comment by Mrfiregem** [comment]
As a workaround, I used the Github releases feed since they link to the blog, but having the full article would be much better.

**Comment by rgwood** [comment]
Yeah, this would be great. The website currently uses [VuePress](https://vuepress.vuejs.org/) and it looks like there are a few RSS plugins out there for VuePress. PRs would be very welcome.

**Comment by rgwood** [comment]
Hi, this is done! We've got RSS/Atom/JSON feeds for the blog now:

https://www.nushell.sh/rss.xml
https://www.nushell.sh/feed.atom
https://www.nushell.sh/feed.json
