### ISSUE TITLE
Document available time specifiers on `date format` page

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell.github.io#896]
It's not clear what are available for now. Maybe it's worth to add just a link to a page where they are already listed.

BTW, what about to compare them somewhere with [these](https://www.gnu.org/software/coreutils/manual/html_node/Time-conversion-specifiers.html)?

**Comment by fdncred** [comment]
Have you tried `date format --list`?

**Comment by EmilySeville7cfg** [comment]
Thanks! This solves my question.
