### ISSUE TITLE
Old command output in command docs

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell.github.io#90]
A few commands need to have their outputs updated. I was looking at `prepend`, for example.

It shows:

```
> open continents.txt | lines
━━━┯━━━━━━━━━━━━━━━
 # │
───┼───────────────
 0 │ Africa
 1 │ South America
 2 │ Australia
 3 │ Europe
 4 │ Antarctica
━━━┷━━━━━━━━━━━━━━━
```

I believe this is old and should not use the mixed table drawing or the empty header.

This probably needs to be updated in the command docs on the main repo first, and then regenerated for the website.

**Comment by hustcer** [comment]
I think the outputs should be updated, let's close it
