### ISSUE TITLE
website footer doesn't point to where to provide feedback

### ISSUE THREAD

**Issue by marianoguerra** [nushell/nushell.github.io#97]
hi! 

https://www.nushell.sh/ says at the bottom

>  If you have suggestions or want to change something please give us feedback 

it would be nice if it linked/pointed to where that is

I found it because I was looking for a place to ask some basic questions about nushell without filling an issue and only found that on the site.

If there's a community (discord/slack/forum) it could point there or to a page where it lists the best place to provide feedback for the site and for nushell

I'm willing to make a PR once I know what should be done, let me know :)

**Comment by rgwood** [comment]
@marianoguerra These days the Nushell Discord seems the most active: https://discord.gg/NtAbbGn

I'm pretty sure the core team would welcome a PR.

**Comment by fdncred** [comment]
thanks!
